apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 210Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain   # Delete
  hostPath:
    path: /mnt/data/postgres

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Mi
