apiVersion: apps/v1
kind: Deployment
metadata:
  name: polls-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polls
  template:
    metadata:
      labels:
        app: polls
    spec:
      initContainers:  # Add the initContainers section here
      - name: init
        image: catalincostea/django-voting-app
        # image: local-registry/django-polls:latest
        # imagePullPolicy: Never
        env:
          - name: SECRET_KEY
            value: "mysecretkey"
          - name: POSTGRES_DB
            value: pollsdb
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
        command: ["/bin/sh"]
        args: ["-c", "./start.sh"]
      containers:
      - name: django-polls
        image: catalincostea/django-voting-app
        # image: local-registry/django-polls:latest
        # imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
          - name: SECRET_KEY
            value: "mysecretkey"
          - name: POSTGRES_DB
            value: pollsdb
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
        # command: ["/bin/sh"]
        # args: ["-c", "tail -f /dev/null"]
        # args: ["-c", "./start.sh"]
        command: ["uwsgi"]
        args: ["--ini", "uwsgi.ini"]

---
apiVersion: v1
kind: Service
metadata:
  name: polls-service
spec:
  selector:
    app: polls
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8000
    nodePort: 30090
