name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t catalincostea/django-voting-app:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          # echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push catalincostea/django-voting-app:latest

      # - name: Deploy to Kubernetes
      #   uses: appleboy/kubectl-action@v0.2.0
      #   with:
      #     kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
      #     command: apply
      #     args: -f kubernetes/deployment.yaml

      # - name: Check deployment status
      #   run: kubectl rollout status deployment/django-voting-app --kubeconfig=${{ secrets.KUBE_CONFIG_DATA }}
